PACKAGE_MANAGER = cargo

build:
	$(PACKAGE_MANAGER) build

check:
	$(PACKAGE_MANAGER) --version

install:
	echo "This language downloads binaries while building"

run:
	$(PACKAGE_MANAGER) run

clean:
	$(PACKAGE_MANAGER) clean
