INTERPRETER = python3

build:
	echo "This language is an interpreted one :D"

check:
	$(INTERPRETER) -v

run:
	$(INTERPRETER) main.py

clean:
	echo "This language does not create binaries (atleast by default)"
